// <auto-generated />
using System;
using Kolia.Thumbnail.API.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kolia.Thumbnail.API.Data.Migrations
{
    [DbContext(typeof(ThumbnailDbContext))]
    [Migration("20260720021229_ChangeUniqueIndex")]
    partial class ChangeUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.AIs.AIFunctionConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FunctionType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Temperature")
                        .HasPrecision(3, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FunctionType")
                        .IsUnique();

                    b.HasIndex("Id", "IsDeleted");

                    b.ToTable("AIFunctionConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-7000-8000-000000000001"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FunctionType = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0002-7000-8000-000000000002"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FunctionType = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0003-7000-8000-000000000003"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FunctionType = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0004-7000-8000-000000000004"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FunctionType = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0005-7000-8000-000000000005"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FunctionType = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0006-7000-8000-000000000006"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FunctionType = 6,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.AIs.AIFunctionConfigItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIProviderConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FunctionConfigId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double?>("Temperature")
                        .HasPrecision(3, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AIProviderConfigurationId");

                    b.HasIndex("AIProviderId");

                    b.HasIndex("FunctionConfigId", "Priority")
                        .IsUnique();

                    b.HasIndex("Id", "IsDeleted");

                    b.ToTable("AIFunctionConfigItems", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.AIs.AIProviderConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ApiKeyHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExtraSettingsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTokenResetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(120);

                    b.Property<long>("TotalTokensUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("AIProviderId", "Name")
                        .IsUnique();

                    b.HasIndex("Id", "IsDeleted");

                    b.ToTable("AIProviderConfigurations", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.AIs.AIProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "IsDeleted");

                    b.HasIndex("Name", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("ShortName", "IsDeleted")
                        .IsUnique();

                    b.ToTable("AIProviders", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Briefs.ContentBriefEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalSheetUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HighlightDataOutput")
                        .HasColumnType("text");

                    b.Property<int?>("ImportSource")
                        .HasColumnType("integer");

                    b.Property<string>("ImportedExternalLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImportedFileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImportedRawText")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyDataInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSheetSyncTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MainMessageOutput")
                        .HasColumnType("text");

                    b.Property<string>("OverviewInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SheetImportedText")
                        .HasColumnType("text");

                    b.Property<string>("SuggestedKeywordsJson")
                        .HasColumnType("text");

                    b.Property<string>("TopicOutput")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ViewpointInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ContentBriefs", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Characters.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Characters.CharacterImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AngleLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpressionLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterImages", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.CompletePackages.CompletePackageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayTextSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SelectedThumbnailId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SelectedThumbnailId");

                    b.ToTable("CompletePackages", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.CompletePackages.CompletePackageTitleEntity", b =>
                {
                    b.Property<Guid>("CompletePackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoTitleOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("CompletePackageId", "VideoTitleOptionId");

                    b.HasIndex("VideoTitleOptionId");

                    b.ToTable("CompletePackageTitles", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DisplayTextRequestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceNewsItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisplayTextRequestId");

                    b.HasIndex("SourceNewsItemId");

                    b.ToTable("DisplayTextOptions", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DisplayTextRequests", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextRequestNewsItemEntity", b =>
                {
                    b.Property<Guid>("DisplayTextRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uuid");

                    b.HasKey("DisplayTextRequestId", "NewsItemId");

                    b.HasIndex("NewsItemId");

                    b.ToTable("DisplayTextRequestNewsItems", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ExternalRequests.ExternalRequestQueueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProviderConfigurationIdUsed")
                        .HasColumnType("uuid");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status", "NextRetryAt");

                    b.ToTable("ExternalRequestQueues", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ExternalRequests.ExternalRequestUsageLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AIProviderType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long?>("EstimatedTokenUsage")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SocialMediaProviderType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecordedDate");

                    b.ToTable("ExternalRequestUsageLogs", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsDeepAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmotionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmotionTags")
                        .HasColumnType("integer");

                    b.Property<string>("ExpectationLongTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectationShortTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacroEventSummaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketReactionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MissingDataNote")
                        .HasColumnType("text");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SentimentOverviewJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WasTranslatedFromForeign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("NewsItemId")
                        .IsUnique();

                    b.ToTable("NewsDeepAnalyses", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmotionPotentialScore")
                        .HasColumnType("integer");

                    b.Property<int>("ImportanceImpactScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelectedByTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MarketType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("NewsSearchRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("NoveltyDataScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Recommendation")
                        .HasColumnType("integer");

                    b.Property<int>("RelevanceLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RelevanceToTopicScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScannedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SuggestedKeywordsForThumbnail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SummaryOverview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewsSearchRequestId");

                    b.HasIndex("ProjectId");

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsSearchRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountFilter")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KeywordsRaw")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MarketScope")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuggestedKeywordsUsedJson")
                        .HasColumnType("text");

                    b.Property<int>("TimeRange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("NewsSearchRequests", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrusted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("RssOrFeedUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("NewsSources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0001-7000-8000-000000000001"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsTrusted = true,
                            Name = "VnExpress",
                            Priority = 1,
                            Region = 1,
                            RssOrFeedUrl = "https://vnexpress.net/rss/kinh-doanh.rss"
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-7000-8000-000000000002"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsTrusted = true,
                            Name = "CoinDesk",
                            Priority = 2,
                            Region = 2,
                            RssOrFeedUrl = "https://www.coindesk.com/arc/outboundfeeds/rss/"
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-7000-8000-000000000003"),
                            CreationTime = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsTrusted = true,
                            Name = "Federal Reserve",
                            Priority = 3,
                            Region = 2,
                            RssOrFeedUrl = "https://www.federalreserve.gov/feeds/press_all.xml"
                        });
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStepNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastActivityTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailCoverUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NeedsApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OutputSummaryText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StepStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "StepNumber")
                        .IsUnique();

                    b.ToTable("ProjectSteps", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Socials.SocialMediaProviderConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ApiBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApiKeyHash")
                        .HasColumnType("text");

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AppId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AppSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BearerToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastRateLimitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastRequestResetTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RateLimitCooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SocialMediaProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRequest")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocialMediaProviderId", "Name")
                        .IsUnique();

                    b.ToTable("SocialMediaProviderConfigurations", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Socials.SocialMediaProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("ShortName", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SocialMediaProviders", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CharacterSnapshotName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayTextSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("GeneratedThumbnailSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPushedToTitleStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastEditRequestText")
                        .HasColumnType("text");

                    b.Property<int?>("LastEditTool")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentGeneratedThumbnailId")
                        .HasColumnType("uuid");

                    b.Property<int>("VariantIndex")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("WasDownloaded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("GeneratedThumbnailSetId");

                    b.HasIndex("ParentGeneratedThumbnailId");

                    b.ToTable("GeneratedThumbnails", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailSetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ThumbnailGenerationRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailGenerationRequestId");

                    b.ToTable("GeneratedThumbnailSets", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestDisplayTextEntity", b =>
                {
                    b.Property<Guid>("ThumbnailGenerationRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisplayTextOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("ThumbnailGenerationRequestId", "DisplayTextOptionId");

                    b.HasIndex("DisplayTextOptionId");

                    b.ToTable("ThumbnailGenerationRequestDisplayTexts", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeableElementsJson")
                        .HasColumnType("text");

                    b.Property<string>("ChangesRequestText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedPromptText")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedElementsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ratio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RequestedImageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ThumbnailGenerationRequests", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestReferenceEntity", b =>
                {
                    b.Property<Guid>("ThumbnailGenerationRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThumbnailLibraryItemId")
                        .HasColumnType("uuid");

                    b.HasKey("ThumbnailGenerationRequestId", "ThumbnailLibraryItemId");

                    b.HasIndex("ThumbnailLibraryItemId");

                    b.ToTable("ThumbnailGenerationRequestReferences", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayTextStyleNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChosenForGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ThumbnailFactorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThumbnailLibraryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("TitleTextAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoTitleAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailLibraryItemId")
                        .IsUnique();

                    b.ToTable("ThumbnailAnalyses", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailLibraryItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFilteredIrrelevant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KeywordBatchTag")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MarketType")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ThumbnailSearchRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ThumbnailSearchRequestId");

                    b.ToTable("ThumbnailLibraryItems", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailSearchRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortFilter")
                        .HasColumnType("integer");

                    b.Property<int>("TimeFilter")
                        .HasColumnType("integer");

                    b.Property<bool>("WasSuggestedFromNews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ThumbnailSearchRequests", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleFeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppliedToRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoTitleRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoTitleRequestId");

                    b.ToTable("VideoTitleFeedbacks", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenerationRound")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoTitleRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoTitleRequestId");

                    b.ToTable("VideoTitleOptions", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuiltPromptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenerationRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KeywordsRaw")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestedTitleCount")
                        .HasColumnType("integer");

                    b.Property<int>("Style")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("VideoTitleRequests", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestNewsItemEntity", b =>
                {
                    b.Property<Guid>("VideoTitleRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewsItemId")
                        .HasColumnType("uuid");

                    b.HasKey("VideoTitleRequestId", "NewsItemId");

                    b.HasIndex("NewsItemId");

                    b.ToTable("VideoTitleRequestNewsItems", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestThumbnailEntity", b =>
                {
                    b.Property<Guid>("VideoTitleRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GeneratedThumbnailId")
                        .HasColumnType("uuid");

                    b.HasKey("VideoTitleRequestId", "GeneratedThumbnailId");

                    b.HasIndex("GeneratedThumbnailId");

                    b.ToTable("VideoTitleRequestThumbnails", (string)null);
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.AIs.AIFunctionConfigItemEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.AIs.AIProviderConfigurationEntity", "AIProviderConfiguration")
                        .WithMany()
                        .HasForeignKey("AIProviderConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.AIs.AIProviderEntity", "AIProvider")
                        .WithMany()
                        .HasForeignKey("AIProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.AIs.AIFunctionConfigEntity", "FunctionConfig")
                        .WithMany("Items")
                        .HasForeignKey("FunctionConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIProvider");

                    b.Navigation("AIProviderConfiguration");

                    b.Navigation("FunctionConfig");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.AIs.AIProviderConfigurationEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.AIs.AIProviderEntity", "AIProvider")
                        .WithMany("Configurations")
                        .HasForeignKey("AIProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AIProvider");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Briefs.ContentBriefEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithOne("ContentBrief")
                        .HasForeignKey("Kolia.Thumbnail.API.Data.Entities.Briefs.ContentBriefEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Characters.CharacterImageEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Characters.CharacterEntity", "Character")
                        .WithMany("Images")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.CompletePackages.CompletePackageEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("CompletePackages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailEntity", "SelectedThumbnail")
                        .WithMany()
                        .HasForeignKey("SelectedThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SelectedThumbnail");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.CompletePackages.CompletePackageTitleEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.CompletePackages.CompletePackageEntity", "CompletePackage")
                        .WithMany("SelectedTitles")
                        .HasForeignKey("CompletePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleOptionEntity", "VideoTitleOption")
                        .WithMany()
                        .HasForeignKey("VideoTitleOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompletePackage");

                    b.Navigation("VideoTitleOption");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextOptionEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextRequestEntity", "DisplayTextRequest")
                        .WithMany("Options")
                        .HasForeignKey("DisplayTextRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.News.NewsItemEntity", "SourceNewsItem")
                        .WithMany()
                        .HasForeignKey("SourceNewsItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DisplayTextRequest");

                    b.Navigation("SourceNewsItem");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextRequestEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("DisplayTextRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextRequestNewsItemEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextRequestEntity", "DisplayTextRequest")
                        .WithMany("SelectedNewsItems")
                        .HasForeignKey("DisplayTextRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.News.NewsItemEntity", "NewsItem")
                        .WithMany()
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DisplayTextRequest");

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ExternalRequests.ExternalRequestQueueEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsDeepAnalysisEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.News.NewsItemEntity", "NewsItem")
                        .WithOne("DeepAnalysis")
                        .HasForeignKey("Kolia.Thumbnail.API.Data.Entities.News.NewsDeepAnalysisEntity", "NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsItemEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.News.NewsSearchRequestEntity", "NewsSearchRequest")
                        .WithMany("NewsItems")
                        .HasForeignKey("NewsSearchRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsSearchRequest");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsSearchRequestEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("NewsSearchRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectStepEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("Steps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Socials.SocialMediaProviderConfigurationEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Socials.SocialMediaProviderEntity", "SocialMediaProvider")
                        .WithMany("Configurations")
                        .HasForeignKey("SocialMediaProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialMediaProvider");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailSetEntity", "GeneratedThumbnailSet")
                        .WithMany("Variants")
                        .HasForeignKey("GeneratedThumbnailSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailEntity", "ParentGeneratedThumbnail")
                        .WithMany("ChildVersions")
                        .HasForeignKey("ParentGeneratedThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GeneratedThumbnailSet");

                    b.Navigation("ParentGeneratedThumbnail");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailSetEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestEntity", "ThumbnailGenerationRequest")
                        .WithMany("GeneratedSets")
                        .HasForeignKey("ThumbnailGenerationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThumbnailGenerationRequest");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestDisplayTextEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextOptionEntity", "DisplayTextOption")
                        .WithMany()
                        .HasForeignKey("DisplayTextOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestEntity", "ThumbnailGenerationRequest")
                        .WithMany("SelectedDisplayTextOptions")
                        .HasForeignKey("ThumbnailGenerationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplayTextOption");

                    b.Navigation("ThumbnailGenerationRequest");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Characters.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("ThumbnailGenerationRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestReferenceEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestEntity", "ThumbnailGenerationRequest")
                        .WithMany("SelectedReferenceItems")
                        .HasForeignKey("ThumbnailGenerationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailLibraryItemEntity", "ThumbnailLibraryItem")
                        .WithMany()
                        .HasForeignKey("ThumbnailLibraryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThumbnailGenerationRequest");

                    b.Navigation("ThumbnailLibraryItem");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailAnalysisEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailLibraryItemEntity", "ThumbnailLibraryItem")
                        .WithOne("Analysis")
                        .HasForeignKey("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailAnalysisEntity", "ThumbnailLibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThumbnailLibraryItem");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailLibraryItemEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("ThumbnailLibraryItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailSearchRequestEntity", "ThumbnailSearchRequest")
                        .WithMany("LibraryItems")
                        .HasForeignKey("ThumbnailSearchRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("ThumbnailSearchRequest");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailSearchRequestEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("ThumbnailSearchRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleFeedbackEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestEntity", "VideoTitleRequest")
                        .WithMany("Feedbacks")
                        .HasForeignKey("VideoTitleRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoTitleRequest");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleOptionEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestEntity", "VideoTitleRequest")
                        .WithMany("Options")
                        .HasForeignKey("VideoTitleRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoTitleRequest");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", "Project")
                        .WithMany("VideoTitleRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestNewsItemEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.News.NewsItemEntity", "NewsItem")
                        .WithMany()
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestEntity", "VideoTitleRequest")
                        .WithMany("SelectedNewsItems")
                        .HasForeignKey("VideoTitleRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("VideoTitleRequest");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestThumbnailEntity", b =>
                {
                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailEntity", "GeneratedThumbnail")
                        .WithMany()
                        .HasForeignKey("GeneratedThumbnailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestEntity", "VideoTitleRequest")
                        .WithMany("SelectedThumbnails")
                        .HasForeignKey("VideoTitleRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedThumbnail");

                    b.Navigation("VideoTitleRequest");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.AIs.AIFunctionConfigEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.AIs.AIProviderEntity", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Characters.CharacterEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.CompletePackages.CompletePackageEntity", b =>
                {
                    b.Navigation("SelectedTitles");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.DisplayTexts.DisplayTextRequestEntity", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("SelectedNewsItems");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsItemEntity", b =>
                {
                    b.Navigation("DeepAnalysis");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.News.NewsSearchRequestEntity", b =>
                {
                    b.Navigation("NewsItems");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Projects.ProjectEntity", b =>
                {
                    b.Navigation("CompletePackages");

                    b.Navigation("ContentBrief");

                    b.Navigation("DisplayTextRequests");

                    b.Navigation("NewsSearchRequests");

                    b.Navigation("Steps");

                    b.Navigation("ThumbnailGenerationRequests");

                    b.Navigation("ThumbnailLibraryItems");

                    b.Navigation("ThumbnailSearchRequests");

                    b.Navigation("VideoTitleRequests");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Socials.SocialMediaProviderEntity", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailEntity", b =>
                {
                    b.Navigation("ChildVersions");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.GeneratedThumbnailSetEntity", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.ThumbnailGeneration.ThumbnailGenerationRequestEntity", b =>
                {
                    b.Navigation("GeneratedSets");

                    b.Navigation("SelectedDisplayTextOptions");

                    b.Navigation("SelectedReferenceItems");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailLibraryItemEntity", b =>
                {
                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.Thumbnails.ThumbnailSearchRequestEntity", b =>
                {
                    b.Navigation("LibraryItems");
                });

            modelBuilder.Entity("Kolia.Thumbnail.API.Data.Entities.VideoTitles.VideoTitleRequestEntity", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Options");

                    b.Navigation("SelectedNewsItems");

                    b.Navigation("SelectedThumbnails");
                });
#pragma warning restore 612, 618
        }
    }
}
